# -*- coding: utf-8 -*-
"""UnSupervised Learning in Space using Autoencoders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIvgSm3acSRCj6MBhra7edRttSV75QPG
"""

# If needed (Colab usually has them)
!pip install seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, roc_auc_score

import tensorflow as tf
from tensorflow.keras import layers, models

df = pd.read_csv("dataset.csv")

print("Dataset Shape:", df.shape)
df.head()

y = df['anomaly']
X = df.drop(['anomaly', 'channel', 'segment'], axis=1)

# Train-test split (important: keep labels aligned)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scaling ONLY features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Keep only NORMAL data for training
X_train_normal = X_train[y_train == 0]

print("Training only on normal samples:", X_train_normal.shape)

print(y_train.value_counts())

input_dim = X_train.shape[1]

autoencoder = models.Sequential([
    layers.Dense(16, activation='relu', input_shape=(input_dim,)),
    layers.Dense(8, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(input_dim, activation='linear')
])

autoencoder.compile(optimizer='adam', loss='mse')

autoencoder.summary()

history = autoencoder.fit(
    X_train_normal, X_train_normal,
    epochs=50,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

# Train error (IMPORTANT for threshold)
train_recon = autoencoder.predict(X_train_normal)
train_mse = np.mean(np.power(X_train_normal - train_recon, 2), axis=1)

# Threshold from training data
threshold = np.percentile(train_mse, 95)
print("Threshold:", threshold)

# Reconstruction on test data
test_recon = autoencoder.predict(X_test)

test_mse = np.mean(np.power(X_test - test_recon, 2), axis=1)

# Predictions
y_pred = (test_mse > threshold).astype(int)

print("Confusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()



fpr, tpr, _ = roc_curve(y_test, test_mse)
auc = roc_auc_score(y_test, test_mse)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {auc:.3f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

def classify_risk(error, threshold):
    if error < threshold:
        return "NORMAL"
    elif error < threshold * 1.5:
        return "WARNING"
    else:
        return "CRITICAL"

def decision_system(risk_level):
    if risk_level == "NORMAL":
        return "Continue normal operation"

    elif risk_level == "WARNING":
        return "Monitor subsystem closely"

    elif risk_level == "CRITICAL":
        return "Trigger alert and corrective action"

results = []

for i in range(len(test_mse)):
    error = test_mse[i]

    risk = classify_risk(error, threshold)
    action = decision_system(risk)

    results.append([error, risk, action])

decision_df = pd.DataFrame(results, columns=["Error", "Risk Level", "Action"])

decision_df.head()

plt.figure(figsize=(8,5))
sns.countplot(x="Risk Level", data=decision_df)
plt.title("Risk Level Distribution")
plt.show()